# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Potret Suisbapeduli (cakbudi_)
email: bagus@teknik.io
description: > # this means to ignore newlines until "baseurl:"
  Suisbapeduli - Senyum Mereka Adalah Kebahagiaan Kami
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://suisbapeduli.github.io" # the base hostname & protocol for your site
permalink: /:categories/:title.html
#twitter_username: bagus18
#github_username:  bagus18

# Build settings
markdown: kramdown
